### ISSUE TITLE
feedback on provide, require, bindings

### ISSUE THREAD

**Issue by acarrico** [andmkent/datatype#8]
Here: https://gist.github.com/acarrico/c8348f7e20c9087c769ce0367dcbd518

**Comment by pnwamk** [comment]
`provide` doesn't work because the macros build some data structures that are used in constructing and verifying type-case instances and this was done in a somewhat sloppy way (e.g. they're not provided, etc). You should be able to make it work by using `(provide (all-defined-out))` or, since I believe the name of the data structure is predictable, you could manually provide it (yuck): `(provide Expr-specific-ADT-type-case)`

As for matching w/o destructuring the data, that just wasn't one of the goals I had in mind when I threw this together. You could certainly add it w/o much work (relatively speaking) I would think.

More generally, as for the state of the repository, I think I mentioned it should not be considered as being in a stable state but that I intended to work on it more at some later point... It seems more likely that I will not revisit this code anytime soon, FYI -- so if you wanted to explore more elegant solutions, extensions, etc you welcome to do what you wish with the code. I should probably update the repo to indicate it's largely ignored status... and perhaps free up the name `datatype` in case someone has a serious package that would find that name useful.

**Comment by acarrico** [comment]
Thanks for the update. With turnstile https://bitbucket.org/stchang/macrotypes and rascal https://github.com/lexi-lambda/rascal there are definitely other functional ideas going around. Your datatypes seems to hit some low-hanging fruit for Typed Racket proper.
